<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-23T22:20:28 EST" name="FrontierSuite" finished-at="2025-01-23T22:20:41 EST" duration-ms="12681">
    <groups>
    </groups>
    <test started-at="2025-01-23T22:20:28 EST" name="TestWithChrome" finished-at="2025-01-23T22:20:38 EST" duration-ms="10280">
      <class name="tests.FrontierValidAddressCheckTest">
        <test-method is-config="true" signature="setUpBrowserAndApp(java.lang.String,java.lang.String)[pri:0, instance:tests.FrontierValidAddressCheckTest@48bb62]" started-at="2025-01-23T22:20:28 EST" name="setUpBrowserAndApp" finished-at="2025-01-23T22:20:33 EST" duration-ms="4609" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://www.frontier.com]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBrowserAndApp -->
        <test-method signature="checkAvailability()[pri:0, instance:tests.FrontierValidAddressCheckTest@48bb62]" started-at="2025-01-23T22:20:33 EST" name="checkAvailability" finished-at="2025-01-23T22:20:37 EST" duration-ms="4364" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.FrontierValidAddressCheckTest.checkAvailability(FrontierValidAddressCheckTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkAvailability -->
        <test-method is-config="true" signature="cleanUp()[pri:0, instance:tests.FrontierValidAddressCheckTest@48bb62]" started-at="2025-01-23T22:20:38 EST" name="cleanUp" finished-at="2025-01-23T22:20:38 EST" duration-ms="439" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- tests.FrontierValidAddressCheckTest -->
    </test> <!-- TestWithChrome -->
    <test started-at="2025-01-23T22:20:28 EST" name="TestWithFirefox" finished-at="2025-01-23T22:20:41 EST" duration-ms="12681">
      <class name="tests.FrontierValidAddressCheckTest">
        <test-method is-config="true" signature="setUpDataSources()[pri:0, instance:tests.FrontierValidAddressCheckTest@72bc6553]" started-at="2025-01-23T22:20:28 EST" name="setUpDataSources" finished-at="2025-01-23T22:20:28 EST" duration-ms="391" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpDataSources -->
        <test-method is-config="true" signature="setUpBrowserAndApp(java.lang.String,java.lang.String)[pri:0, instance:tests.FrontierValidAddressCheckTest@72bc6553]" started-at="2025-01-23T22:20:28 EST" name="setUpBrowserAndApp" finished-at="2025-01-23T22:20:37 EST" duration-ms="8632" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://www.frontier.com]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBrowserAndApp -->
        <test-method signature="checkAvailability()[pri:0, instance:tests.FrontierValidAddressCheckTest@72bc6553]" started-at="2025-01-23T22:20:37 EST" name="checkAvailability" finished-at="2025-01-23T22:20:39 EST" duration-ms="2364" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.FrontierValidAddressCheckTest.checkAvailability(FrontierValidAddressCheckTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkAvailability -->
        <test-method is-config="true" signature="cleanUp()[pri:0, instance:tests.FrontierValidAddressCheckTest@72bc6553]" started-at="2025-01-23T22:20:40 EST" name="cleanUp" finished-at="2025-01-23T22:20:41 EST" duration-ms="959" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- tests.FrontierValidAddressCheckTest -->
    </test> <!-- TestWithFirefox -->
  </suite> <!-- FrontierSuite -->
</testng-results>
